parameters:
#    arii_jid.example.class: Arii\JOCBundle\Example

services:
#    arii_jid.example:
#        class: %arii_jid.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    arii_joc.sos:
        class: Arii\JOCBundle\Service\AriiSOS
        arguments: ["@arii_core.db", "@arii_core.sql"]

    arii_joc.treegrid:
        class: Arii\JOCBundle\Service\AriiTreeGrid
        arguments: []

    arii_joc.state:
        class: Arii\JOCBundle\Service\AriiState
        arguments: ["@doctrine.orm.default_entity_manager", "@arii_core.db", "@arii_core.sql", "@arii_core.date"]

    arii_joc.focus2:
        class: Arii\JOCBundle\Service\AriiFocus2
        arguments: [ "@arii_core.tools", "@doctrine.orm.default_entity_manager" ]

# V2 en ORM
    arii.joc:
        class: Arii\JOCBundle\Service\AriiJOC
        arguments: [ "@arii_core.portal", @doctrine, "@arii_core.requests" ]

# Obsolete
    arii_joc.focus:
        class: Arii\JOCBundle\Service\AriiFocus
        arguments: [ "@arii_core.tools", "@arii_core.db" ]

