# --------------------------------------------------------------------------
# PAGES PRINCIPALES
# --------------------------------------------------------------------------
arii_Time_index:
    path:  /
    defaults: { _controller: AriiTimeBundle:Default:index }

arii_Time_readme:
    path:  /readme
    defaults: { _controller: AriiTimeBundle:Default:readme }

xml_Time_toolbar:
    path:  /toolbar.xml
    defaults: { _controller: AriiTimeBundle:Default:toolbar }

json_Time_ribbon:
    path:  /ribbon.json
    defaults: { _controller: AriiTimeBundle:Default:ribbon }

xml_Time_menu:
    path:  /menu.xml
    defaults: { _controller: AriiTimeBundle:Default:menu }

xml_Time_context_menu:
    path:  /context_menu.xml
    defaults: { _controller: AriiTimeBundle:Default:menu }

# --------------------------------------------------------------------------
# ZONES
# --------------------------------------------------------------------------
arii_Time_zones:
    path:  /zones
    defaults: { _controller: AriiTimeBundle:Zones:index }

xml_Time_zones:
    path:  /zones/grid.xml
    defaults: { _controller: AriiTimeBundle:Zones:grid }

xml_Time_zones_tree:
    path:  /zones/tree.xml
    defaults: { _controller: AriiTimeBundle:Zones:tree }

xml_Time_zones_toolbar:
    path:  /zones/toolbar.xml
    defaults: { _controller: AriiTimeBundle:Zones:toolbar }

xml_Time_zones_form:
    path:  /zones/form.xml
    defaults: { _controller: AriiTimeBundle:Zones:form }

xml_Time_zones_select:
    path:  /zones/select.xml
    defaults: { _controller: AriiTimeBundle:Zones:select }

xml_Time_countries_select:
    path:  /countries/select.xml
    defaults: { _controller: AriiTimeBundle:Zones:countries }
        
xml_Time_zone_save:
    path:  /zone/save.xml
    defaults: { _controller: AriiTimeBundle:Zones:save }
    
# --------------------------------------------------------------------------
# REFERENCES
# --------------------------------------------------------------------------
arii_Time_references:
    path:  /references
    defaults: { _controller: AriiTimeBundle:References:index }

xml_Time_references:
    path:  /references/grid.xml
    defaults: { _controller: AriiTimeBundle:References:grid }

xml_Time_references_tree:
    path:  /references/tree.xml
    defaults: { _controller: AriiTimeBundle:References:tree }

xml_Time_references_list:
    path:  /references/list.xml
    defaults: { _controller: AriiTimeBundle:References:list }

xml_Time_references_form:
    path:  /references/form.xml
    defaults: { _controller: AriiTimeBundle:References:form }

xml_Time_references_rules:
    path:  /references/rules.xml
    defaults: { _controller: AriiTimeBundle:References:rules }

xml_Time_references_add_rule:
    path:  /references/add_rule.xml
    defaults: { _controller: AriiTimeBundle:References:add_rule }

xml_Time_references_del_rule:
    path:  /references/del_rule.xml
    defaults: { _controller: AriiTimeBundle:References:del_rule }

# --------------------------------------------------------------------------
# CALENDARS
# --------------------------------------------------------------------------
arii_Time_calendars:
    path:  /calendars
    defaults: { _controller: AriiTimeBundle:Calendars:index }

xml_Time_calendars_toolbar:
    path:  /calendars/toolbar.xml
    defaults: { _controller: AriiTimeBundle:Calendars:toolbar }

xml_Time_calendars:
    path:  /calendars/grid.xml
    defaults: { _controller: AriiTimeBundle:Calendars:grid }

xml_Time_calendars_form:
    path:  /calendars/form.xml
    defaults: { _controller: AriiTimeBundle:Calendars:form }

xml_Time_calendar_test:
    path:  /calendars/test.xml
    defaults: { _controller: AriiTimeBundle:Calendars:test }

xml_Time_calendar_test_schedule:
    path:  /calendars/schedule.xml
    defaults: { _controller: AriiTimeBundle:Calendars:schedule }
# --------------------------------------------------------------------------
# RULES
# --------------------------------------------------------------------------
arii_Time_rules:
    path:  /rules
    defaults: { _controller: AriiTimeBundle:Rules:index }

xml_Time_rules_toolbar:
    path:  /rules/toolbar.xml
    defaults: { _controller: AriiTimeBundle:Rules:toolbar }

xml_Time_rules:
    path:  /rules/grid.xml
    defaults: { _controller: AriiTimeBundle:Rules:grid }

xml_Time_rules_form:
    path:  /rules/form.xml
    defaults: { _controller: AriiTimeBundle:Rules:form }

xml_Time_rule_test:
    path:  /rules/test.xml
    defaults: { _controller: AriiTimeBundle:Rules:test }

xml_Time_rule_save:
    path:  /rules/save.xml
    defaults: { _controller: AriiTimeBundle:Rules:save }

xml_Time_rule_test_schedule:
    path:  /rules/schedule.xml
    defaults: { _controller: AriiTimeBundle:Rules:schedule }

# --------------------------------------------------------------------------
# DAYS
# --------------------------------------------------------------------------
arii_Time_days:
    path:  /days
    defaults: { _controller: AriiTimeBundle:Days:index }

xml_Time_days:
    path:  /days/grid.xml
    defaults: { _controller: AriiTimeBundle:Days:grid }

# --------------------------------------------------------------------------
# HOLIDAYS
# --------------------------------------------------------------------------
arii_Time_holidays:
    path:  /holidays
    defaults: { _controller: AriiTimeBundle:Holidays:index }

xml_Time_holidays:
    path:  /holidays/list.xml
    defaults: { _controller: AriiTimeBundle:Holidays:list }
