arii_ACK_index:
    path:  /
    defaults: { _controller: AriiACKBundle:Default:index }

arii_ACK_readme:
    path:  /readme
    defaults: { _controller: AriiACKBundle:Default:readme }

json_ACK_ribbon:
    path:  /ribbon.json
    defaults: { _controller: AriiACKBundle:Default:ribbon }

json_ACK_menu:
    path:  /menu.json
    defaults: { _controller: AriiACKBundle:Default:menu }
    
xml_ACK_toolbar:
    path:  /toolbar.xml
    defaults: { _controller: AriiACKBundle:Default:toolbar }

xml_ACK_tree:
    path:  /tree.xml
    defaults: { _controller: AriiACKBundle:Default:tree }

arii_ACK_alarms_list:
    path:  /alarms/list.xml
    defaults: { _controller: AriiACKBundle:Alarms:list }

arii_ACK_alarms_add:
    path:  /alarms/add/{id}
    defaults: { _controller: AriiACKBundle:Alarms:add }

#============================================================
# Notifications
#------------------------------------------------------------
arii_ACK_notifications:
    path:  /notifications
    defaults: { _controller: AriiACKBundle:Notifications:index }
    
xml_ACK_notifications_grid:
    path:  /notifications/grid.xml
    defaults: { _controller: AriiACKBundle:Notifications:grid }

xml_ACK_notifications_toolbar2:
    path:  /notifications/toolbar2.xml
    defaults: { _controller: AriiACKBundle:Notifications:toolbar2 }

xml_ACK_notifications_tree:
    path:  /notifications/tree.xml
    defaults: { _controller: AriiACKBundle:Notifications:tree }

xml_ACK_notifications_select:
    path:  /notifications/select.xml
    defaults: { _controller: AriiACKBundle:Notifications:select }

html_ACK_notifications_import:
    path:  /notifications/import.html
    defaults: { _controller: AriiACKBundle:Notifications:import }

txt_ACK_notifications:
    path:  /public/notifications.{ext}
    defaults: { _controller: AriiACKBundle:Notifications:get, ext: txt }
    
xls_ACK_notifications:
    path:  /notifications.xls
    defaults: { _controller: AriiACKBundle:Notifications:get, ext: xls }

html_ACK_notifications_check:
    path:  /public/notifications/check.html
    defaults: { _controller: AriiACKBundle:Notifications:check}

#============================================================
# Notification
#------------------------------------------------------------
xml_ACK_notification_form:
    path:  /notification/form.xml
    defaults: { _controller: AriiACKBundle:Notifications:form}

xml_ACK_notification_save:
    path:  /notification/save.xml
    defaults: { _controller: AriiACKBundle:Notifications:save}

xml_ACK_notification_delete:
    path:  /notification/delete.xml
    defaults: { _controller: AriiACKBundle:Notifications:delete}

xml_ACK_notification_toolbar:
    path:  /notification/toolbar.xml
    defaults: { _controller: AriiACKBundle:Notifications:toolbar}

#============================================================
# Events
#------------------------------------------------------------
arii_ACK_events:
    path:  /events
    defaults: { _controller: AriiACKBundle:Events:index }
    
xml_ACK_events_grid:
    path:  /events/grid.xml
    defaults: { _controller: AriiACKBundle:Events:grid }

xml_ACK_events_grid_menu:
    path:  /events/grid_menu.xml
    defaults: { _controller: AriiACKBundle:Events:grid_menu}
    
json_ACK_events_count:
    path:  /events/count.json
    defaults: { _controller: AriiACKBundle:Events:count }
    
#============================================================
# Event
#------------------------------------------------------------
xml_ACK_event_form:
    path:  /event/form.xml
    defaults: { _controller: AriiACKBundle:Events:form}

xml_ACK_event_save:
    path:  /event/save.xml
    defaults: { _controller: AriiACKBundle:Events:save}

xml_ACK_event_delete:
    path:  /event/delete.xml
    defaults: { _controller: AriiACKBundle:Events:delete}

xml_ACK_event_toolbar:
    path:  /event/toolbar.xml
    defaults: { _controller: AriiACKBundle:Events:toolbar}

txt_ACK_event_state:
    path:  /event/state.txt
    defaults: { _controller: AriiACKBundle:Events:state}

#============================================================
# Alarms
#------------------------------------------------------------
arii_ACK_alarms:
    path:  /alarms
    defaults: { _controller: AriiACKBundle:Alarms:index }
    
xml_ACK_alarms_grid:
    path:  /alarms/grid.xml
    defaults: { _controller: AriiACKBundle:Alarms:grid }

xml_ACK_alarms_grid_menu:
    path:  /alarms/grid_menu.xml
    defaults: { _controller: AriiACKBundle:Alarms:grid_menu}
    
#============================================================
# Alarms
#------------------------------------------------------------
xml_ACK_alarm_form:
    path:  /alarm/form.xml
    defaults: { _controller: AriiACKBundle:Alarms:form}

xml_ACK_alarm_save:
    path:  /alarm/save.xml
    defaults: { _controller: AriiACKBundle:Alarms:save}

xml_ACK_alarm_delete:
    path:  /alarm/delete.xml
    defaults: { _controller: AriiACKBundle:Alarms:delete}

xml_ACK_alarm_toolbar:
    path:  /alarm/toolbar.xml
    defaults: { _controller: AriiACKBundle:Alarms:toolbar}

txt_ACK_alarm_state:
    path:  /alarm/state.txt
    defaults: { _controller: AriiACKBundle:Alarms:state}

#============================================================
# Alerts
#------------------------------------------------------------
arii_ACK_alerts:
    path:  /alerts
    defaults: { _controller: AriiACKBundle:Alerts:index }
    
xml_ACK_alerts_grid:
    path:  /alerts/grid.xml
    defaults: { _controller: AriiACKBundle:Alerts:grid }

xml_ACK_alerts_grid_menu:
    path:  /alerts/grid_menu.xml
    defaults: { _controller: AriiACKBundle:Alerts:grid_menu}
    
#============================================================
# Alert
#------------------------------------------------------------
xml_ACK_alert_form:
    path:  /alert/form.xml
    defaults: { _controller: AriiACKBundle:Alerts:form}

xml_ACK_alert_save:
    path:  /alert/save.xml
    defaults: { _controller: AriiACKBundle:Alerts:save}

xml_ACK_alert_delete:
    path:  /alert/delete.xml
    defaults: { _controller: AriiACKBundle:Alerts:delete}

xml_ACK_alert_toolbar:
    path:  /alert/toolbar.xml
    defaults: { _controller: AriiACKBundle:Alerts:toolbar}

txt_ACK_alert_state:
    path:  /alert/state.txt
    defaults: { _controller: AriiACKBundle:Alerts:state}

#============================================================
# Jobs
#------------------------------------------------------------
arii_ACK_jobs:
    path:  /jobs
    defaults: { _controller: AriiACKBundle:Jobs:index }
    
xml_ACK_jobs_grid:
    path:  /jobs/grid.xml
    defaults: { _controller: AriiACKBundle:Jobs:grid }

json_ACK_jobs_count:
    path:  /jobs/count.json
    defaults: { _controller: AriiACKBundle:Jobs:count }

#============================================================
# Job
#------------------------------------------------------------
xml_ACK_job_form:
    path:  /job/form.xml
    defaults: { _controller: AriiACKBundle:Jobs:form}

xml_ACK_job_save:
    path:  /job/save.xml
    defaults: { _controller: AriiACKBundle:Jobs:save}

xml_ACK_job_delete:
    path:  /job/delete.xml
    defaults: { _controller: AriiACKBundle:Jobs:delete}

xml_ACK_job_toolbar:
    path:  /job/toolbar.xml
    defaults: { _controller: AriiACKBundle:Jobs:toolbar}


#============================================================
# Actions
#------------------------------------------------------------
arii_ACK_actions:
    path:  /actions
    defaults: { _controller: AriiACKBundle:Actions:index }
    
xml_ACK_actions_grid:
    path:  /actions/grid.xml
    defaults: { _controller: AriiACKBundle:Actions:grid }


#============================================================
# Network
#--------------------------------------------------------------------
arii_ACK_network:
    path:  /network
    defaults: { _controller: AriiACKBundle:Network:index }

xml_ACK_network_grid:
    path:  /network/grid.xml
    defaults: { _controller: AriiACKBundle:Network:grid }

xml_ACK_network_pie:
    path:  /network/pie.xml
    defaults: { _controller: AriiACKBundle:Network:pie }

html_ACK_network_info:
    path:  /network/info.html
    defaults: { _controller: AriiACKBundle:Network:info }

json_ACK_network_count:
    path:  /network/count.json
    defaults: { _controller: AriiACKBundle:Network:count }
    
#============================================================
# Host
#--------------------------------------------------------------------
xml_ACK_host_form:
    path:  /host/form.xml
    defaults: { _controller: AriiACKBundle:Network:form}
#============================================================
# Synchro
#--------------------------------------------------------------------
 